StartupEvents.registry(`block`, (event) => {
	event.create(`shovel`)
		.box(0, 0, 0, 16, 1, 16)
		.noItem()
		.defaultTranslucent()
		.noCollision()
	event.create(`tablet`)
		.box(0, 0, 0, 16, 1, 16)
		.noItem()
		.defaultTranslucent()
		.noCollision()
	event.create(`machine`)
		.tagBlock(`mineable/pickaxe`)
	event.create(`energy_fairy`)
		.lightLevel(1.0)
		.noItem()
	event.create(`active_zapper`)
		.lightLevel(0.4)
	event.create(`inactive_zapper`)
})

StartupEvents.registry(`item`, (event) => {
	event.create(`electronic_parts`)
		.displayName(`Circuit Board`)
	event.create(`tablet`, `pickaxe`)
		.tier(`wood`)
		.maxDamage(4)
	event.create(`bosss_id_card`)
		.displayName(`Boss's ID Card`)
	event.create(`energy_fairy`)
		.maxDamage(200)
})
